# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15          # PostgreSQL version
    environment:
      POSTGRES_USER: admin     # Database username
      POSTGRES_PASSWORD: 123456! # Database password
      POSTGRES_DB: mydb        # Database name
    ports:
      - "5432:5432"             # Map host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data even if container stops
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:               # Named volume for data persistence
